/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Boton: typeof import('./src/components/Boton.vue')['default']
    CardNoticias: typeof import('./src/components/CardNoticias.vue')['default']
    Casilla: typeof import('./src/components/Games/Casilla.vue')['default']
    GamexRaya: typeof import('./src/components/Games/GamexRaya.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PracticaOne: typeof import('./src/components/PracticaOne.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
